repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.12.0
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
      - id: check-merge-conflict
